### ISSUE TITLE
Feature - change swipe action

### ISSUE THREAD

**Issue by octoshrimpy** [Livinglist/Hacki#111]
Would be nice to change swipe action on stories to one of the up/down/share/flag actions, not just pin to top

**Comment by Livinglist** [comment]
Hi there, thanks for suggesting new features! The reason I didn't put those actions on story tile is because it is only logic to upvote/downvote/flag/share after you tap into the story, this could be reconsidered though. 
(Reminder: you can perform those actions by swiping to right on the story's title inside the comments screen!)

**Comment by octoshrimpy** [comment]
I often share stories based on title alone, either a link to HN story, or a link to the external content. having that as an option would be great. 

I also favorite (or save for later) certain stories based on the same criteria, haha
