### ISSUE TITLE
Add an option to mark stories as read when the user scrolled past them

### ISSUE THREAD

**Issue by ghost** [Livinglist/Hacki#162]

**Comment by AtmanActive** [comment]
+1

The problem is that either HackerNews or Hacki inserts stories among already seen stories so it is NOT strictly chronological, unfortunately.

So, if I read/scroll until I see a grayed out story (which means I did click on it before), then, there's a gotcha that, for example, three stories down there IS a story I never saw before, even though it is below the one I already saw.

Hence I'm forced to eyeball each and every entry just to make sure I didn't miss something. Ridiculous. Alternatively, I could open each and every entry just to make sure it stays grayed out going forward, but that's too cumbersome.

So, a simple, optional "mark as seen on scrolled up" which would auto-mark as seen as soon as the entry is no longer visible on my screen would be a perfect solution.

Thanks.

**Comment by AtmanActive** [comment]
As of 2023-09-25, this newly implemented feature works only on the first run. And it was awesome when it worked. Unfortunately, on every subsequent app run, it doesn't work anymore.

Please double-check and issie a fix.

Thanks.

**Comment by Livinglist** [comment]
@AtmanActive what’s the version of system and app are you on?

**Comment by AtmanActive** [comment]
Hacki v1.9.0

Android version: 13

Thanks!

**Comment by AtmanActive** [comment]
Can confirm: working great in version 1.9.2.

Woohoo! :-)

Thank you for this awesome app.
