### ISSUE TITLE
Comments not loading

### ISSUE THREAD

**Issue by pjgatt** [Livinglist/Hacki#363]
Today it seems there's been trouble loading comments on stories. The HN web page seems to load fine and comments load fine, not sure if they've changed something.

Android 14, latest app version.

**Comment by Livinglist** [comment]
yep I just found out too, working on the fix.

![image](https://github.com/Livinglist/Hacki/assets/7277662/ac9f99db-9f24-4511-a840-f2a7b5d39191)

**Comment by Livinglist** [comment]
I just released v1.6.2 with the fix for this bug. It gonna take some time before the build is approved and distributed on Google Play, F-Droid or App Store. 

If you are on Android and can't wait for the fix, you can try installing APK file from the latest release: https://github.com/Livinglist/Hacki/releases/tag/v2.6.2
