### ISSUE TITLE
On First Comment Collapse, Subsequent Top Level Comments Fail To Load

### ISSUE THREAD

**Issue by ZeroCool2u** [Livinglist/Hacki#50]
I'm on a Pixel 6 Pro stock Android stable.

When you collapse the first comment tree in a thread, the subsequent comments do not load when you scroll down. You must uncollapse the top comment, then scroll down to get the comments to load. I'm not sure I'd call this a bug, but I'd prefer an option to more aggressively load comment content. Maybe a middle ground between the full blown offline mode and the current implementation.

Love the app and thanks for the hard work and frequent updates!

**Comment by Efreak** [comment]
I've noticed this too, sometimes on collapsing comments, the next set of comments doesn't immediately load. It appears that Hacki continues loading comments in order, loading nested threads that have been hidden instead of the next current-or-higher level comment that isn't shown yet. When I collapse the top comment, the counter on it sometimes increases for quite a while before loading the next top level comment.

When using other HN clients, it appears that top level comments are loaded first, then top level replies. Usually third- or fourth-level comments are collapsed automatically and sometimes not loaded until expanded manually. It doesn't usually take long enough to matter to me, but I can see it being annoying on slower connections, slower devices, etc.

**Comment by Livinglist** [comment]
From the current implementation of `CommentsCubit` which is the component managing the state of story screen (aka comments screen), it is quite challenging to allow loading parent comments without waiting for previous comments to be loaded first. After some considerations, I have decided to add sorting feature to story screen so that user can sort the parent comments (comments posted directly under the story) by post date.

**Comment by ZeroCool2u** [comment]
Sorry, I was out of town all weekend and didn't see any of your replies until now. 

Thanks so much for looking into this. If you need me to test anything please let me know.
